const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';
const NEW_ATTACHMENT = 'NEW_ATTACH'
const NEW_REQUEST = 'NEW_REQUEST';
const NEW_MESSAGE = 'NEW_MESSAGE';
const TYPING = 'IS_TYPING';
const STOP_TYPING = 'STOP_TYPING';
const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";
const ONLINE_USER = "ONLINE_USER";

export {
    ALERT,
    REFETCH_CHATS,
    NEW_MESSAGE_ALERT,
    NEW_ATTACHMENT,
    NEW_REQUEST,
    NEW_MESSAGE,
    TYPING,
    STOP_TYPING,
    CHAT_JOINED,
    CHAT_LEAVED,
    ONLINE_USER
}